site:
  title: Antora Docs
  start_page: component-b::index.adoc  # Adjust as needed

content:
  sources:
    - url: https://github.com/croweigibson/antora-test/tree/master/content
      start_path: .  # Folder where index.adoc is located

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
